iOS. Fix click outside of popup/dialog
JetBrains/compose-multiplatform-core pull request #1060
Opened 2024-02-06 19:32 UTC by igordmn

## Proposed Changes
By the description of this [pointInside](https://developer.apple.com/documentation/uikit/uiview/1622533-pointinside) - it is not a callback, it is a hit test function. So, it can be called even if click outside of the view.

Replacing it by touch callbacks

## Testing
Manual on iOS demo App (components -> material3 -> AlertDialog).

## Issues Fixed
https://github.com/JetBrains/compose-multiplatform-core/assets/5963351/c862adf0-c9f8-484a-b5a8-35c6486b8cb1

It seems reproducible not everywhere (I tested on iOS 14 x86 simulator)

2024-02-06 19:37 UTC, dima-avdeev-jb approved these changes

2024-02-06 19:41 UTC, dima-avdeev-jb commented on compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/UIViewComposeSceneLayer.uikit.kt
>              return focusable
If focusable will be false, touchesBegan and touchesEnded will never calls

2024-02-06 19:42 UTC, dima-avdeev-jb requested changes
I think it is better to my continue this branch

2024-02-06 19:53 UTC, igordmn commented on compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/UIViewComposeSceneLayer.uikit.kt
>              return focusable
Should we just remove it?

2024-02-06 20:22 UTC, MatkovIvan commented on compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/UIViewComposeSceneLayer.uikit.kt
>              return focusable
focusable layer should block clicks under it

2024-02-06 20:36 UTC, igordmn commented on compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/UIViewComposeSceneLayer.uikit.kt
>              return focusable
Understood.  Nevertheless `pointInside` still looks like not the right place to handle the events. Maybe we can consume all events inside `touchesBegan` 🤔.

Also, as far as I remember, native view bounds can be different from Composable content bounds, so to be correct we have to also check bound intersection.

2024-02-06 20:49 UTC, MatkovIvan commented on compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/UIViewComposeSceneLayer.uikit.kt
>              return focusable
> Nevertheless pointInside still looks like not the right place to handle the events

True

> we have to also check bounds intersection

Not in this case. Here we have ecplicitly full-screen vew to filter/catch input outside of Dialog/Popup. Dialog/Popup is inside another platform view that receive regular (in the bounds) input.

2024-02-08 11:24 UTC, igordmn commented
Closed in favour of https://github.com/JetBrains/compose-multiplatform-core/pull/1079

2024-02-08 11:24 UTC, closed without merging