iOS a11y dialogues and popus integration
JetBrains/compose-multiplatform-core pull request #1091
Opened 2024-02-09 12:23 UTC by elijah-semyonov

## Proposed Changes

Integrate popup and dialogues with a11y.
Add `setEscapeEventListener` to `ComposeSceneLayer` for semantic escape, aka "get me out of here if possible"-action incoming from accessibility-based input.

## Testing

Test: N/A

2024-02-09 12:34 UTC, MatkovIvan requested changes
`setEscapeEventListener` doesn't look as good API and requirement for this interface.
Also, there are 3 more implementations that don't seem updated at all. CI should fail.

2024-02-09 12:34 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/window/Dialog.skiko.kt
> +    val onEscapeEvent = if (properties.dismissOnBackPress || properties.dismissOnClickOutside) {
It should not depend on `dismissOnClickOutside`

2024-02-09 12:34 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/ComposeSceneLayer.skiko.kt
It's a public API, dump should be regenerated

2024-02-09 12:34 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/scene/ComposeSceneLayer.skiko.kt
> +    fun setEscapeEventListener(
It doesn't seem required to expose this method to public API. It duplicates existing functionality of other event handlers.

2024-02-09 12:35 UTC, MatkovIvan commented
@elijah-semyonov I suggest you just generate Esc key event without changing of current APIs / dialogs implementation

2024-02-09 12:41 UTC, dima-avdeev-jb approved these changes

2024-02-10 07:48 UTC, dima-avdeev-jb commented
@elijah-semyonov You should run `./gradlew :ui:apiDump` to update API dump

2024-02-12 11:04 UTC, elijah-semyonov commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/window/Dialog.skiko.kt
> +    val onEscapeEvent = if (properties.dismissOnBackPress || properties.dismissOnClickOutside) {
It should, that's basically the semantics of the action.

2024-02-12 15:32 UTC, MatkovIvan approved these changes

2024-02-12 15:32 UTC, MatkovIvan commented on compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.desktop.kt
> +
Please revert desktop file

2024-02-12 23:00 UTC, dima-avdeev-jb approved these changes

2024-02-13 08:08 UTC, merged