Add predictive back support for iOS
JetBrains/compose-multiplatform-core pull request #1432
Opened 2024-07-05 10:18 UTC by LukasAnda

Describe proposed changes and the issue being fixed

## Testing
I tested thoroughly on a sample project on both iOS and Android

This should be tested by QA

## Release Notes
### Feature - iOS
- Added support for Predictive back, now swiping back on iOS correctly shows progress to the previous screen

## Google CLA
You need to sign the Google Contributor’s License Agreement at https://cla.developers.google.com/.
This is needed since we synchronise most of the code with Google’s AOSP repository. Signing this agreement allows us to synchronise code from your Pull Requests as well.

2024-07-08 08:07 UTC, MatkovIvan requested changes
Thanks for a contribution.

But this approach won't work and cannot be merged. A few issues here:
- Changes in Android in fork
- A few new common public APIs
- Adding APIs in modules that they shouldn't belong to

All of these are blockers - we cannot do such changes in the fork (we do not publish android binaries).

We're in the process with colleagues from Google to make this feature happen, but currently there is no decision about the shape of common public APIs. So once unblocked, I'll use this as a reference (if you're OK with it), but I cannot accept this PR as-is

2024-07-08 08:07 UTC, MatkovIvan commented on compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/window/BackEventCompat.kt
> +class BackEventCompat @VisibleForTesting constructor(
We shouldn't introduce a new public classes on Android

2024-07-08 08:07 UTC, MatkovIvan commented on compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/window/BackEventHandler.kt
> +val LocalBackEventHandler = staticCompositionLocalOf<BackEventHandler> {
Adding public **common** API in fork won't work - we do NOT re-compile/publish android artifact but using binary redirection to original Google's library instead

2024-07-08 08:07 UTC, MatkovIvan commented on navigation/navigation-compose/src/commonMain/kotlin/androidx/navigation/compose/PredictiveBackHandler.kt
> +expect fun PredictiveBackHandler(
It shouldn't be placed as part of this module because `BackHandler` logic is also handled in non-compose navigation modules.

(+ another common API)

2024-11-19 22:47 UTC, gregriggins36 commented
This makes sense @MatkovIvan 
Is there any timeline for the proper predictive back implementation?

2025-01-16 17:38 UTC, terrakok commented
https://github.com/JetBrains/compose-multiplatform-core/pull/1771

2025-01-16 17:38 UTC, closed without merging