TF2 floating cursor
JetBrains/compose-multiplatform-core pull request #1598
Opened 2024-09-26 11:59 UTC by alexzhirkevich

This should be enough for iOS TF2 floating cursor to work. 
Can't build it to test because of №2 developer mistake - early Mac update :(

## Release Notes

### iOS - Features
- Floating cursor support for BasicTextField(TextFieldState)

2025-02-10 12:41 UTC, ASalavei commented
@alexzhirkevich , is the MR still in a draft state, or we should review it?
Current'y, we're experimenting with adoption of the `UITextInput` to make direct connection between iOS and Compose input, that will solve lots of issues, including floating cursor: https://youtrack.jetbrains.com/issue/CMP-7103

2025-02-10 13:03 UTC, alexzhirkevich commented
Hi. You can review this, it is quite small and just enables cursor from the old text field
You can also take a look at new haptics i added yesterday - #1831. There are nice new feedback types that i had to implement manually before
> we're experimenting with adoption of the UITextInput

Sounds awesome, it there an active branch?

2025-02-12 10:27 UTC, mazunin-v-jb commented
LGTM. Actually, this fix is useful despite the textfield experiment: it forwards TextLayoutResult, which is required for many UITextInput methods.

@m-sasha, could you please also review Skiko part?

2025-02-12 10:27 UTC, mazunin-v-jb approved these changes

2025-02-12 13:11 UTC, ASalavei commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/PlatformTextInputMethodRequest.skiko.kt
> +    val textLayoutResult : Flow<TextLayoutResult>
```suggestion
    val textLayoutResult: Flow<TextLayoutResult>
```

2025-02-12 15:02 UTC, m-sasha reviewed
We've been passing data from `platformSpecificTextInputSession` to the `PlatformTextInputService`s via direct calls on `PlatformTextInputSession` (e.g. `notifyFocusedRect`), but I think doing it with a flow instead is better, because it means in cases where the data isn't needed, it won't be computed.

2025-02-12 15:02 UTC, m-sasha commented on compose/foundation/foundation/src/skikoMain/kotlin/androidx/compose/foundation/text/input/internal/TextInputSession.skiko.kt
> +                textLayoutResult = snapshotFlow(layoutState::layoutResult).filterNotNull(),
Are you sure we don't want to forward `null`s to the text input service? I'm not entirely sure when the layout can be `null`, but isn't it possible the text input service will remain stuck with a stale non-null value if we're filtering `null`s?

2025-02-12 15:08 UTC, m-sasha commented
Let's run the CI, and I think we can merge if it passes.

2025-02-12 18:03 UTC, alexzhirkevich commented on compose/foundation/foundation/src/skikoMain/kotlin/androidx/compose/foundation/text/input/internal/TextInputSession.skiko.kt
> +                textLayoutResult = snapshotFlow(layoutState::layoutResult).filterNotNull(),
I'm not completely sure, but `notifyFocusedRect` you mentioned above does also ignore null rects. And  PlatformTextInputService for TF1 [is not notified](https://github.com/JetBrains/compose-multiplatform-core/blob/289e332d2372e4597b8f6c51ae5bc08055deb8a7/compose/ui/ui-text/src/commonMain/kotlin/androidx/compose/ui/text/input/TextInputService.kt#L355) about null layouts too

2025-02-13 14:26 UTC, m-sasha approved these changes

2025-02-13 15:43 UTC, ASalavei requested changes

2025-02-13 15:43 UTC, ASalavei commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/PlatformTextInputMethodRequest.skiko.kt
> +    val textLayoutResult: Flow<TextLayoutResult>
With this change you need to update API dump. Please run `./gradlew desktopApiDump`.

2025-02-14 16:16 UTC, alexzhirkevich commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/PlatformTextInputMethodRequest.skiko.kt
> +    val textLayoutResult: Flow<TextLayoutResult>
done

2025-02-14 20:45 UTC, ASalavei commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/PlatformTextInputMethodRequest.skiko.kt
> +    val textLayoutResult: Flow<TextLayoutResult>
Thanks!
@m-sasha , could you please re-approve API updates?

2025-02-14 20:47 UTC, m-sasha approved these changes

2025-02-14 20:47 UTC, ASalavei approved these changes

2025-02-17 10:52 UTC, merged