Use new `GraphicsLayer` for all rendering
JetBrains/compose-multiplatform-core pull request #1754
Opened 2024-12-20 12:47 UTC by MatkovIvan

Remove `RenderNodeLayer`, fix clipping and shadows behavior

Fixes CMP-6616, CMP-6617, CMP-7216

## Testing
More tests TBD

## Release Notes
### Fixes - Multiple Platforms
- TBD

2025-01-08 17:00 UTC, igordmn requested changes
Before merging, we should decide if it is okay to change the lighting approach.

2025-01-08 17:00 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
I compared it with Android, looks the same 👍

Windows:
![Windows](https://github.com/user-attachments/assets/20d8f239-780e-47a1-bcbe-7c737864c4cd)

Android:
![Android](https://github.com/user-attachments/assets/6cde627e-4bd0-4bff-8dd0-69b58ee43f97)

```
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.PressInteraction
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material.Button
import androidx.compose.material.MaterialTheme
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication
import kotlinx.coroutines.delay

fun main() = singleWindowApplication {
    MaterialTheme {
        val interactionSource1 = remember { MutableInteractionSource() }
        val interactionSource2 = remember { MutableInteractionSource() }
        val interactionSource3 = remember { MutableInteractionSource() }
        val interactionSource4 = remember { MutableInteractionSource() }
        Box(Modifier.fillMaxSize().padding(50.dp)) {
            Button({}, Modifier.align(Alignment.TopStart), interactionSource = interactionSource1) {}
            Button({}, Modifier.align(Alignment.TopEnd), interactionSource = interactionSource2) {}
            Button({}, Modifier.align(Alignment.BottomStart), interactionSource = interactionSource3) {}
            Button({}, Modifier.align(Alignment.BottomEnd), interactionSource = interactionSource4) {}
        }

        LaunchedEffect(Unit) {
            delay(1000)
            interactionSource1.emit(PressInteraction.Press(Offset(10f, 10f)))
            interactionSource2.emit(PressInteraction.Press(Offset(10f, 10f)))
            interactionSource3.emit(PressInteraction.Press(Offset(10f, 10f)))
            interactionSource4.emit(PressInteraction.Press(Offset(10f, 10f)))
        }
    }
}
```

Though, this change can be controversial for big screens, like on Desktop. Shadows for far buttons looks weird (too sharp and too far away from the button). It is okay for Android because of small screens (the spec authors and Android devs might didn't take large screens into account)

We might check what Flutter does, or/and try to tweak parameters/approach in a way that it looks less sharp on large screens. Coerce light offset by some value? Tweak zRatio? Apply zRatio to shadowRadius?

2025-01-08 17:00 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +    density: Density,
(after deciding what to do in the other comment) Let's change release notes to:
```
Fix light position for during shadow rendering to match [the Material specification](https://m2.material.io/design/environment/light-shadows.html#light) and Android behaviour
```
And provide screenshots before/after:

![New](https://github.com/user-attachments/assets/ea43b412-e7fb-4feb-b458-146a7498b809)
![Old](https://github.com/user-attachments/assets/42aa2c79-131b-4501-a942-2b709c9d29a5)

2025-01-08 17:00 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +    density: Density,
No matter that it is part of the platform/foundation layer, `elevation`/`shadow` feature was added in Android 5.0 exactly for material design.

2025-01-08 17:20 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
> It is okay for Android because of small screens

 It's the same on tablets
 
> what Flutter does

It behaves differently - a light source there is relative to each shape + it's exposed to public API

> try to tweak parameters/approach in a way that it looks less sharp on large screens. Coerce light offset by some value? Tweak zRatio? Apply zRatio to shadowRadius?

I believe that it should be consistent across platforms. If we need to do such things it's better to collaborate with Google and expose it as a public common API.
I'm strongly against magic numbers here

2025-01-08 17:42 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
>  It's the same on tablets

Tablets are not as big as desktops. I checked on 4K with density 1.5. Tablets have a greater density, and so, this issue can be not visible there, as light source isn't far away of the components.

> I believe that it should be consistent across platforms.

User experience should be in more priority than consistency. Better to aim to achieve both, but if we can't, we should take user experience as the requirement, and consistency is just one of the way to achieve requirements. Technical implementation shouldn't dictate how things should look.

> I'm strongly against magic numbers here

The current algorithm looks to me tweaked as well. The numbers I believe were tweaked to look good on Android devices.

> Google and expose it as a public common API.

It is a months/years story. We should decide something now. I don't think that the current PR way is good looking for desktop, we can consult with others and find a compromise.


> It behaves differently - a light source there is relative to each shape

Could you elaborate more? I didn't understood it.

2025-01-08 17:45 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
> It is okay for Android because of small screens

Adoption of larger screen IS here, see line 380

> Could you elaborate more?

They have an explicit public offset parameter for each shadow

2025-01-08 19:13 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
agreed to tweak slightly this way in a separate PR:
```
radius = LIGHT_RADIUS.toPx() * zWeightedAdjustment,
```

2025-01-08 19:15 UTC, igordmn approved these changes

2025-01-08 19:27 UTC, merged

2025-01-08 20:02 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
Looks like there is a mistake somewhere 🤔. I rechecked on small sizes, without the radius fix, with density = 2. There is a difference with Android:

https://github.com/user-attachments/assets/23499540-c722-43df-883e-84c512c64f7b

2025-01-09 10:19 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/platform/GraphicsLayerOwnerLayer.skiko.kt
> +internal fun SkiaGraphicsContext.setLightingInfo(
> There is a difference with Android

Just checked - there is no difference here. Let's continue this thread offline