Restore commonMain to AOSP state (material3 formatting)
JetBrains/compose-multiplatform-core pull request #1760
Opened 2024-12-20 19:30 UTC by igordmn

Partially fixes https://youtrack.jetbrains.com/issue/CMP-5740/Upstreaming.-compilation.-other-fixes

Restore to the last merged Jetpack Compose (1.8.0-alpha07) and Material3 (1.4.0-alpha04).

## Testing
- CI passes

## Release Notes
N/A

2025-01-06 10:36 UTC, MatkovIvan requested changes

2025-01-06 10:36 UTC, MatkovIvan commented on compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/DateInput.kt
> -internal class DateInputValidator(
It was an intentional change that should be upstreamed. Please revert

2025-01-06 10:36 UTC, MatkovIvan commented on compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/internal/CalendarModel.kt
> -internal fun datePatternAsInputFormat(localeFormat: String): DateInputFormat {
It's a common code that should be upsteamed. Please revert.

2025-01-06 10:36 UTC, MatkovIvan commented on compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/node/TreeSet.kt
> -internal expect class SortedSet<E>(comparator: Comparator<in E>) {
It's intentional renaming to reduce expectations. Please revert

2025-01-17 20:00 UTC, MatkovIvan approved these changes

2025-01-20 08:43 UTC, igordmn commented on compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/DateInput.kt
> -internal class DateInputValidator(
Reverted. Will be upstreamed

2025-01-20 08:43 UTC, igordmn commented on compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/internal/CalendarModel.kt
> -internal fun datePatternAsInputFormat(localeFormat: String): DateInputFormat {
Reverted. Will be upstreamed

2025-01-20 08:43 UTC, igordmn commented on compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/node/TreeSet.kt
> -internal expect class SortedSet<E>(comparator: Comparator<in E>) {
Reverted. Will be upstreamed

2025-01-20 09:55 UTC, merged