Restore commonMain to AOSP state (move from common)
JetBrains/compose-multiplatform-core pull request #1761
Opened 2024-12-20 19:41 UTC by igordmn

Partially fixes https://youtrack.jetbrains.com/issue/CMP-5740/Upstreaming.-compilation.-other-fixes

Restore to the last merged Jetpack Compose (1.8.0-alpha07):
- move additional code from commonMain to skikoMain. It is used only by CMP source sets. Even if it makes sense to be common, upstreaming will take a lot of time.
- implement restored expects

## Testing
- CI passes

## Release Notes
N/A

2025-01-06 10:39 UTC, MatkovIvan requested changes

2025-01-06 10:39 UTC, MatkovIvan commented on compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/AnchoredDraggable.kt
> +internal expect inline fun assertOnJvm(statement: Boolean, message: () -> String): Unit
Intentional change of incorrect AOSP common fix. Please revert.

2025-01-06 10:39 UTC, MatkovIvan commented on compose/animation/animation-core/src/commonMain/kotlin/androidx/compose/animation/core/ArcSpline.kt
> +internal expect inline fun binarySearch(array: FloatArray, position: Float): Int
Intentional fix of incorrect AOSP common fix. Please revert.

2025-01-06 10:39 UTC, MatkovIvan commented on compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/node/TreeSet.kt
> -internal expect class SortedSet<E>(comparator: Comparator<in E>) {
Intentional change. Please revert

2025-01-17 20:03 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/Expect.skiko.kt
Let's use meaningful file names instead of "Expect.kt"

2025-01-17 20:03 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/viewinterop/InteropView.skiko.kt
> +internal expect class InteropViewGroup
Would you mind add YT link with TODO regarding moving it back to commonMain?

2025-01-20 08:24 UTC, igordmn commented on compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/AnchoredDraggable.kt
> +internal expect inline fun assertOnJvm(statement: Boolean, message: () -> String): Unit
Reverted. Will be upstreamed

2025-01-20 08:24 UTC, igordmn commented on compose/animation/animation-core/src/commonMain/kotlin/androidx/compose/animation/core/ArcSpline.kt
> +internal expect inline fun binarySearch(array: FloatArray, position: Float): Int
Reverted. Will be upstreamed

2025-01-20 08:24 UTC, igordmn commented on compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/node/TreeSet.kt
> -internal expect class SortedSet<E>(comparator: Comparator<in E>) {
Reverted. Will be upstreamed

2025-01-20 08:42 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/viewinterop/InteropView.skiko.kt
> +internal expect class InteropViewGroup
Added to https://youtrack.jetbrains.com/issue/CMP-7382/Refactor-InteropView-classes-in-commonMain

By the way, moving to commonMain by itself shouldn't be the goal. We should reuse it in commonMain somewhere as well. Otherwise it will unused in commonMain abstraction.

2025-01-20 08:42 UTC, igordmn commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/Expect.skiko.kt
Done

2025-01-20 13:13 UTC, MatkovIvan commented on compose/ui/ui/src/skikoMain/kotlin/androidx/compose/ui/viewinterop/InteropView.skiko.kt
> +internal expect class InteropViewGroup
Sure. There was a plan to reuse some amount of code instead of copy-pasting

2025-01-20 13:14 UTC, MatkovIvan approved these changes

2025-01-20 14:43 UTC, merged